name: Distr Create Version
description: This action creates a new version of an application in Distr
author: Glasskube

branding:
  icon: heart
  color: red

inputs:
  api-base:
    description: ID of the application that the version will be created in
    required: true
  api-token:
    description: ID of the application that the version will be created in
    required: true
  application-id:
    description: ID of the application that the version will be created in
    required: true
  version-name:
    description: Name of the version that will be created
    required: true
  compose-file:
    description:
      'Path to the Docker Compose File (required for docker applications)'
    required: false
  chart-name:
    description:
      'Helm Chart Name (required for helm applications and if chart-type is
      "repository")'
    required: false
  chart-type:
    description:
      'Helm Chart Type (required for helm applications, allowed: "repository" or
      "oci")'
    required: false
  chart-version:
    description: 'Helm Chart Version (required for helm applications)'
    required: false
  chart-url:
    description: 'Helm Chart URL (required for helm applications)'
    required: false
  base-values-file:
    description: Path to the base values file for helm applications
    required: false
  template-file:
    description: Path to the template file for helm applications
    required: false

outputs:
  created-version-id:
    description: ID of the application version that was created in Distr

runs:
  using: node20
  main: dist/index.js
