name: Continuous Integration

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Create Distr Version
        id: distr-create-version
        uses: ./
        with:
          api-base: ${{ vars.DISTR_API_BASE }}
          api-token: ${{ secrets.DISTR_TOKEN }}
          application-id: ${{ vars.DISTR_APPLICATION_ID }}
          version-name: 'v8.0.0' # ${{ github.ref_name }}
          compose-file: ${{ github.workspace }}/action.yml
          # chart-type: 'oci'
          # chart-url: oci://ghcr.io/stefanprodan/charts/podinfo
          # chart-version: 'v7.0.0'
          # base-values-file: ${{ github.workspace }}/.prettierrc.yml
          template-file: ${{ github.workspace }}/.env.example

      - name: Print Application Version ID
        id: output
        run: echo "${{ steps.distr-create-version.outputs.created-version-id }}"
