name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Read Docker Compose File
        id: read-docker-compose
        run: cat ${{ github.workspace }}/README.md >> $GITHUB_OUTPUT

      - name: Distr App Upload Action (local)
        id: distr-app-upload-action
        uses: ./
        with:
          distr-api-base: ${{ vars.DISTR_API_BASE }}
          distr-api-token: ${{ secrets.DISTR_TOKEN }}
          distr-application-id: ${{ vars.DISTR_APPLICATION_ID }}
          distr-application-version-name: 'v2.0.0' # ${{ github.ref_name }}
          distr-application-version-compose-file: ${{ steps.read-docker-compose.outputs }}
        #env:
        #  DISTR_API_BASE: ${{ vars.DISTR_API_BASE }}
        #  DISTR_TOKEN: ${{ secrets.DISTR_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
